### ISSUE TITLE
Вставка подписей с автонумерацией средствами Word

### ISSUE THREAD

**Issue by MaxBQb** [Inozpavel/IMRY#10]
В конечном итоге должно существовать два тега:
- {{ img src="..." name="..." }}
представляет из себя обычное изображение с автонумеруемой подписью
по типу "Рис. 2 Скин тестов моей программы"
- {{ img_link_2 }} 
обычный тег, но вместо него подставляется ссылка на картинку (как в примере test.docx)

Обязательным условием является возможность использования этих тегов при составлении шаблонов работ

**Comment by MaxBQb** [comment]
Вот [пример вставки подписей](https://coderoad.ru/47411503/%D0%BA%D0%B0%D0%BA-%D0%B2%D1%81%D1%82%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%BF%D0%BE%D0%B4%D0%BF%D0%B8%D1%81%D1%8C-%D0%BA-%D1%82%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D0%B5-%D0%B8-%D1%80%D0%B8%D1%81%D1%83%D0%BD%D0%BA%D1%83-%D0%B2-aspose-word) (нам нужна подпись снизу)
Текст для вставки: `"SEQ Рис. \\* ARABIC"`

**Comment by MaxBQb** [comment]
Поидее при помощи 
`Write("Рис. ")` перед, и
`Write(" "+img_name)` после вставки field 
можно сделать подписи

**Comment by Inozpavel** [comment]
Автонумерация сделана, но не средствами Word. Пакет не позволяет автонумеровать картинки
