### ISSUE TITLE
Преформат-вставка

### ISSUE THREAD

**Issue by MaxBQb** [Inozpavel/IMRY#12]
# Вставка ПКМ по пустому полю
При этом происходит обработка вставляемого текста:
- он тримится по краям (под нож все whilespace последовательности)
Далее всё зависит от поля и ожидаемого формата его содержимого:
- Удаление знаков препинания в конце (для названий работ)
- Добавление точки в конце для:
  - индивидуальных заданий
  - общего задания
  - цели работы
 - Смена регистра (для названий работ)

# Перезапись Shift+ПКМ по полю с любым содержимым
Обработка аналогична предыдущему, наличие содержимого в поле для ввода не проверяется.

# Вызов обработчика для содержимого поля СКМ
(Не обязательная, но желательная часть)
Обработка текущего содержимого поля по правилам см. выше

~Shift+СКМ нету)~

P. S.
> Если у тебя полетели стили заголовка, это заметят не все... 
> Если ты должен каждый раз, добавляя этот заголовок совершать "ритуал обхода", это будет бесить
> Вывод: если программа для автоматизации неудобна в управлении — она бесполезна, как инструмент.

**Comment by MaxBQb** [comment]
Наш девиз н@x!й полумеры.

**Comment by Inozpavel** [comment]
Сделал
СКМ - вставка из буфера, если поле пустое, с форматированием. Если поле не пустое, будет простое форматирование.
Shift + ПКМ - форматирование поля.
