### ISSUE TITLE
Обработка отсутствия работ

### ISSUE THREAD

**Issue by MaxBQb** [Inozpavel/IMRY#3]
# Если в подтянутых работах нет практик или лаб (но что-то второе там есть)
![image](https://user-images.githubusercontent.com/27343275/96162833-b205e400-0f21-11eb-839e-95ea9dd03bea.png)
Панель с генерацией таких работ отображать не нужно
# Как на примере:
![image](https://user-images.githubusercontent.com/27343275/96163064-0dd06d00-0f22-11eb-82c1-5aac46adcbfd.png)

# Если работ нет совсем
![image](https://user-images.githubusercontent.com/27343275/96163226-4cfebe00-0f22-11eb-9780-4b8d6200d1fb.png)
Кидать диалог на то, что шаблон пустой и disable "Создать отчёт" кнопку

# Если работ больше 23 (Число не принципиально)
![image](https://user-images.githubusercontent.com/27343275/96163698-e1692080-0f22-11eb-97c9-48a7993ef5aa.png)
Scrollbar

**Comment by Inozpavel** [comment]
Сделано
![image](https://user-images.githubusercontent.com/61870238/96371688-a0b01800-116b-11eb-945d-d52412955786.png)
![image](https://user-images.githubusercontent.com/61870238/96371724-dc4ae200-116b-11eb-881b-182a8f83feb6.png)
![image](https://user-images.githubusercontent.com/61870238/96371734-e967d100-116b-11eb-84bc-761c0982258c.png)
![image](https://user-images.githubusercontent.com/61870238/96371747-fab0dd80-116b-11eb-9ee7-2323b0d5392b.png)
