### ISSUE TITLE
ReadOnly на файлах кладёт прогу на раз

### ISSUE THREAD

**Issue by MaxBQb** [Inozpavel/IMRY#4]
# ReadOnly на файлах отчётов.. при попытке сгенерировать отчёт программа падает
# Открываем файл конфига программой, потом меняем ему атрибут на "Только чтение", попытка добавить новую работу кладёт программу.
# Адекватным поведение считается:
- Либо предложить пользователю снять атрибут (не ручками)
- Либо прервать действие и попросить ручками снять атрибут (но тогда хотя бы директорию с файлом открыть)

*Для файлов с кодом это по-идее не актуально, так как их мы не меняем.*

**Comment by Inozpavel** [comment]
Исправил
