### ISSUE TITLE
Вставка изображений

### ISSUE THREAD

**Issue by MaxBQb** [Inozpavel/IMRY#7]
**После** обработки {{ past_here_tag }}
Должна происходить обработка тегов img.
Пример {{ img src="./src/Java/images/Test1.png" }} в отчёте должно быть заменено на картинку по текущему пути, либо на пустую строку (в случае любой ошибки)
при этом:
- относительные пути ".\" указывают на папку содержащую конфиги и папку Reports
- абсолютные пути воспринимаются как абсолютные пути.

*На данном этапе считаем, что теги {{ img }} уже присутствуют в шаблоне report.docx*

**Comment by Inozpavel** [comment]
Сделал
