### ISSUE TITLE
Добавление картинок в отчёт

### ISSUE THREAD

**Issue by MaxBQb** [Inozpavel/IMRY#8]
Подобно тому, как мы можем добавить файл с кодом в отчёт, 
мы должны иметь возможность добавить картинку.
 При добавлении файла с картинкой, мы также можем добавить к нему комментарий.
Сюда 
![image](https://user-images.githubusercontent.com/27343275/96547659-27bcd780-12b5-11eb-8ff9-6a40c362dfab.png)

При сборке отчёта из шаблона **ДО** замены тегов {{ img }}, но **ПОСЛЕ** замены обычных тегов 
производится вставка тегов {{ img }} в src добавляется путь до файла, в name подпись для картинки

Примеры:
- {{ img src=".\pic.bmp" name="test my code" }}
- {{ img src=".\pic2.bmp" }}

Соответственно атрибут name должен обрабатываться как подпись к картинке

теги img добавляются в том порядке, в котором расположены в настройках отчёта
code.java
img_test1.png
img_test2.png

или
test_img.bmp
code.asm // hate assembler

**Comment by Inozpavel** [comment]
сделал
